# Generated by Django 3.1.2 on 2021-02-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roddi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='approvals',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='obtained_assets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wish_list',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='user',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Estate',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
