# Generated by Django 3.1.2 on 2021-03-08 14:31

from django.db import migrations, models
import roddi.models


class Migration(migrations.Migration):

    dependencies = [
        ('roddi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.IntegerField(default=roddi.models.Comment._get_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estate',
            name='id',
            field=models.IntegerField(default=roddi.models.Estate._get_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=roddi.models.User._get_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
