# Generated by Django 3.1.2 on 2021-02-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roddi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ObtainedAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='asset',
            name='image_url',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='to_be_distributed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='to_be_donated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='to_be_thrown',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('email', models.EmailField(default='', max_length=254)),
                ('age', models.IntegerField()),
                ('relation_to_dead', models.CharField(default='', max_length=120)),
                ('latest_login', models.DateTimeField(auto_now_add=True)),
                ('comments', models.ManyToManyField(to='roddi.Comment')),
                ('obtained_assets', models.ManyToManyField(to='roddi.ObtainedAsset')),
                ('wish_list', models.ManyToManyField(to='roddi.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='SingleDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(default=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roddi.user')),
            ],
        ),
        migrations.AddField(
            model_name='obtainedasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roddi.asset'),
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(default='')),
                ('approvals', models.ManyToManyField(related_name='approvals', to='roddi.User')),
                ('assets', models.ManyToManyField(to='roddi.Asset')),
                ('users', models.ManyToManyField(to='roddi.User')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roddi.user'),
        ),
        migrations.AddField(
            model_name='asset',
            name='comments',
            field=models.ManyToManyField(to='roddi.Comment'),
        ),
        migrations.AddField(
            model_name='asset',
            name='distribution',
            field=models.ManyToManyField(to='roddi.SingleDistribution'),
        ),
    ]
