# Generated by Django 3.1.2 on 2021-03-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roddi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='send_reminder_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estate',
            name='is_complete',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
