# Generated by Django 3.1.6 on 2021-02-08 13:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roddi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roddi.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roddi.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='wish_list',
            field=models.ManyToManyField(related_name='wish_list', through='roddi.Wish', to='roddi.Asset'),
        ),
    ]
