# Generated by Django 3.1.2 on 2021-02-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roddi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
