# Generated by Django 3.1.2 on 2021-03-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roddi', '0002_auto_20210308_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='distribute_votes',
            field=models.ManyToManyField(blank=True, related_name='distribute_votes', to='roddi.User'),
        ),
        migrations.AddField(
            model_name='asset',
            name='donate_votes',
            field=models.ManyToManyField(blank=True, related_name='donate_votes', to='roddi.User'),
        ),
        migrations.AddField(
            model_name='asset',
            name='throw_votes',
            field=models.ManyToManyField(blank=True, related_name='throw_votes', to='roddi.User'),
        ),
    ]
