# Generated by Django 3.1.2 on 2021-02-03 12:16

from django.db import migrations, models
import django.db.models.deletion
import roddi.models


class Migration(migrations.Migration):

    dependencies = [
        ('roddi', '0002_auto_20210202_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singledistribution',
            name='user',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='distribution',
        ),
        migrations.AddField(
            model_name='asset',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roddi.user'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.IntegerField(default=roddi.models.Asset._get_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='obtained_assets',
            field=models.ManyToManyField(to='roddi.Asset'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wish_list',
            field=models.ManyToManyField(related_name='wish_list', to='roddi.Asset'),
        ),
        migrations.DeleteModel(
            name='ObtainedAsset',
        ),
        migrations.DeleteModel(
            name='SingleDistribution',
        ),
    ]
