# Generated by Django 3.1.2 on 2021-03-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roddi', '0003_auto_20210311_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='relation_to_dead',
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('sibling', 'Sibling'), ('parent', 'Parent'), ('pibling', 'Uncle/Aunt'), ('grandparent', 'Grandparent'), ('child', 'Child'), ('grandchild', 'Grandchild'), ('other', 'Other')], default='other', max_length=120)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roddi.estate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roddi.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='relation_to_dead',
            field=models.ManyToManyField(related_name='relation_to_dead', through='roddi.Relation', to='roddi.Estate'),
        ),
    ]
