# Generated by Django 3.1.2 on 2021-02-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roddi', '0003_auto_20210218_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='estate', to='roddi.Asset'),
        ),
    ]
