# Generated by Django 3.1.2 on 2021-02-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roddi', '0003_auto_20210203_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='asset',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='estate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
